### ISSUE TITLE
HTML/PDF: monospace font too large

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#122]
[document.pdf](https://github.com/metanorma/metanorma-ribose/files/7759496/document.pdf)
[document.presentation.xml.zip](https://github.com/metanorma/metanorma-ribose/files/7759501/document.presentation.xml.zip)

<img width="567" alt="Screenshot 2021-12-22 at 10 21 55 AM" src="https://user-images.githubusercontent.com/11865/147024173-d50728c3-6bfd-4d4d-a296-38dcdfa85ac4.png">

The Monospace font size looks too large. Can we reduce it similar to what we did for OGC? Thanks.

**Comment by ronaldtse** [comment]
Similarly this also occurs in HTML.

<img width="875" alt="Screenshot 2021-12-22 at 10 26 27 AM" src="https://user-images.githubusercontent.com/11865/147024648-c3fe64cf-b3a7-497b-8034-18e996e00be9.png">

**Comment by Intelligent2013** [comment]
Done ([document.presentation.pdf](https://github.com/metanorma/metanorma-ribose/files/7760984): 
![image](https://user-images.githubusercontent.com/5559926/147057048-31a5f43e-54c0-4c83-ab97-d2ff32b31e0e.png)

/document.presentation.pdf)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 . In the PDF, can we also enlarge the text font sizes (normal, monospace, etc)? They are too small compared with normal content text.

<img width="541" alt="Screenshot 2021-12-22 at 4 30 48 PM" src="https://user-images.githubusercontent.com/11865/147061210-9eb8a040-9789-4f34-8d3c-88595211928a.png">

**Comment by opoudjis** [comment]
@ronaldtse can this be closed?

**Comment by ronaldtse** [comment]
Let me double check.

**Comment by ronaldtse** [comment]
@opoudjis the HTML font size isn't fixed yet for "inline monospace".

<img width="855" alt="Screenshot 2021-12-25 at 4 59 07 PM" src="https://user-images.githubusercontent.com/11865/147381594-16bd7ca4-6707-42af-8859-cc741e7bf9f6.png">

**Comment by opoudjis** [comment]
Introduced inline formatting default for monospace size in isodoc/base_style_reset.css

**Comment by ronaldtse** [comment]
Confirmed fix. Thanks.
